version: "3.9"
services:
  directory:
    build:
      context: ./directory-service
    image: jinom/directory-service:local
    container_name: directory
    ports:
      - "9088:8088"

  dps:
    build:
      context: ./speedtest-node
    image: jinom/speedtest-node:local
    container_name: speed-dps
    environment:
      - NODE_ID=node-dps
      - REGION=id-dps
      - ADDR=:8080
    ports:
      - "9080:8080"

  jkt:
    build:
      context: ./speedtest-node
    image: jinom/speedtest-node:local
    container_name: speed-jkt
    environment:
      - NODE_ID=node-jkt
      - REGION=id-jkt
      - ADDR=:8081
    ports:
      - "9081:8081"

  client:
    build:
      context: ./client
    image: jinom/speedtest-client:local
    container_name: speed-client
    ports:
      - "9082:80"
